version: "3.8"
services:
  server:
    build:
      context: ./gpumonitor_server
      dockerfile: Dockerfile
    restart: always 
    container_name: gpumonitor_server
    ports:
      - "7030:7030"
  web:
    build:
      context: ./gpumonitor_web
      dockerfile: Dockerfile
    restart: always 
    container_name: gpumonitor_web
    ports:
      - "31800:80"
    depends_on:
      - server